
CREATE TABLE IF NOT EXISTS `#__jut_btn` (
	`id` INT(5) UNSIGNED NOT NULL auto_increment,
	`name` VARCHAR(20) NOT NULL DEFAULT '',
	`desc` VARCHAR(75) NOT NULL DEFAULT '',
	`icon` VARCHAR(200) NOT NULL DEFAULT '',
	`params` TEXT NOT NULL DEFAULT '',
	`misc` TEXT NOT NULL DEFAULT '',
	`access` TINYINT(1) UNSIGNED NOT NULL DEFAULT '0',
	`ordering` TINYINT(3) NOT NULL DEFAULT '0',
	`published` TINYINT(1) NOT NULL DEFAULT '0',
	PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;
